// <auto-generated />
using System;
using FBCOMSystemManagement.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FBCOMSystemManagement.Migrations
{
    [DbContext(typeof(DBContextFBCOM))]
    [Migration("20221215054137_initial-create")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FBCOMSystemManagement.Models.CPE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMEI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Installed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNAntenne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNRouteur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CPES");
                });

            modelBuilder.Entity("FBCOMSystemManagement.Models.Installation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BandAuto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CELLband")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CPEID")
                        .HasColumnType("int");

                    b.Property<string>("CarteCINRecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarteCINVerso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompteSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DATEIntervention")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributeur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emplacement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPSLatitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GPSLongitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICCID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IMSI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdConnexion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Immeublefibre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Installed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LTEScreen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NGSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Offre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRB_BH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRB_NBH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PVPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureInside")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureOutside")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureOutside2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RSRP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SINR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNRNegative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNRScreen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speed1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speed2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speed3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeedScreen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatueScreen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneBluetooth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TelephoneID")
                        .HasColumnType("int");

                    b.Property<string>("TypeCient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoipScreen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eNodeBID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CPEID");

                    b.HasIndex("TelephoneID");

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("FBCOMSystemManagement.Models.Telephone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Installed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Telephones");
                });

            modelBuilder.Entity("FBCOMSystemManagement.Models.Installation", b =>
                {
                    b.HasOne("FBCOMSystemManagement.Models.CPE", "CPE")
                        .WithMany("Installations")
                        .HasForeignKey("CPEID");

                    b.HasOne("FBCOMSystemManagement.Models.Telephone", "Telephone")
                        .WithMany("Installations")
                        .HasForeignKey("TelephoneID");

                    b.Navigation("CPE");

                    b.Navigation("Telephone");
                });

            modelBuilder.Entity("FBCOMSystemManagement.Models.CPE", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("FBCOMSystemManagement.Models.Telephone", b =>
                {
                    b.Navigation("Installations");
                });
#pragma warning restore 612, 618
        }
    }
}
